### ISSUE TITLE
nitrogenase activity has definition that is not precisely correct and deviates from source

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#22119]
```yaml
id: GO:0016163
name: nitrogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: 8 reduced ferredoxin + 8 H+ + nitrogen + 16 ATP = 8 oxidized ferredoxin + 2 NH3 + 16 ADP + 16 phosphate." [EC:1.18.6.1]
synonym: "iron-iron nitrogenase activity" NARROW []
synonym: "molybdenum-iron nitrogenase activity" NARROW []
synonym: "reduced ferredoxin:dinitrogen oxidoreductase (ATP-hydrolysing) activity" RELATED [EC:1.18.6.1]
synonym: "vanadium-iron nitrogenase activity" NARROW []
xref: EC:1.18.6.1
xref: MetaCyc:NITROGENASE-RXN
xref: RHEA:21448
xref: UM-BBD_enzymeID:e0395
is_a: GO:0016732 ! oxidoreductase activity, acting on iron-sulfur proteins as donors, dinitrogen as acceptor
```

Where did this def come from? It says https://enzyme.expasy.org/EC/1.18.6.1 but it doesn't match. nitrogenase takes dinitrogen as input.

I think where we do cite EC as sole def xref we should auto-check the defs match

But in this case this would be superseded anyway - we have an equivalent rhea, so we should use rhea as the source (which also correctly has dinitrogen)

![image](https://user-images.githubusercontent.com/50745/132552119-b16ab15c-dd13-4482-9b99-3b1de2217910.png)
