### ISSUE TITLE
Add donotannotate to renal system process

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#22378]
See #16143 where we decided to do this for "renal system development"

surely we also want this for

```yaml
id: GO:0003014
name: renal system process
namespace: biological_process
def: "A organ system process carried out by any of the organs or tissues of the renal system. The renal system maintains fluid balance, and contributes to electrolyte balance, acid/base balance, and disposal of nitrogenous waste products. In humans, the renal system comprises a pair of kidneys, a pair of ureters, urinary bladder, urethra, sphincter muscle and associated blood vessels; in other species, the renal system may comprise related structures (e.g., nephrocytes and malpighian tubules in Drosophila)." [GOC:cjm, GOC:mtg_cardio, GOC:mtg_kidney_jan10]
synonym: "excretory system process" EXACT []
synonym: "kidney system process" RELATED []
is_a: GO:0003008 ! system process
```

note that the ones below likely refer to the vertebrate renal system, possibly specifically the upper urinary tract

```yaml
id: GO:0072048
name: renal system pattern specification
namespace: biological_process
def: "Any developmental process that results in the creation of defined areas or spaces within an organism to which cells respond and eventually are instructed to differentiate into the anatomical structures of the renal system." [GOC:mtg_kidney_jan10]
synonym: "renal system pattern formation" RELATED [GOC:mtg_kidney_jan10]
is_a: GO:0007389 ! pattern specification process
relationship: part_of GO:0072001 ! renal system development

id: GO:0001977
name: renal system process involved in regulation of blood volume
namespace: biological_process
def: "A slow mechanism of blood pressure regulation that responds to changes in pressure resulting from fluid and salt intake by modulating the quantity of blood in the circulatory system." [GOC:dph, GOC:tb, ISBN:0721643949]
synonym: "renal blood volume control of blood pressure" RELATED []
synonym: "renal regulation of blood volume" RELATED [GOC:dph, GOC:tb]
is_a: GO:0003071 ! renal system process involved in regulation of systemic arterial blood pressure
relationship: part_of GO:0050878 ! regulation of body fluid levels
```
