### ISSUE TITLE
Remove EC xrefs for molecular function regulators

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#22502]
prompted by https://github.com/geneontology/pathways2GO/issues/141 I am looking at the mappings for some generic ECs like 2.7.1

The xref and definition xref on the regulator doesn't make any sense to me:

```
id: GO:0008607
name: phosphorylase kinase regulator activity
namespace: molecular_function
def: "Modulation of the activity of the enzyme phosphorylase kinase." [EC:2.7.11.19]
synonym: "phosphorylase kinase, intrinsic regulator activity" NARROW []
xref: EC:2.7.1.-
intersection_of: GO:0003674 ! molecular_function
intersection_of: regulates GO:0004689 ! phosphorylase kinase activity

id: GO:0004689
name: phosphorylase kinase activity
namespace: molecular_function
alt_id: GO:0008606
def: "Catalysis of the reaction: 4 ATP + 2 phosphorylase b = 4 ADP + phosphorylase a." [EC:2.7.11.19]
synonym: "ATP:phosphorylase-b phosphotransferase activity" RELATED [EC:2.7.11.19]
synonym: "dephosphophosphorylase kinase activity" RELATED [EC:2.7.11.19]
synonym: "glycogen phosphorylase kinase activity" RELATED [EC:2.7.11.19]
synonym: "PHK" RELATED [EC:2.7.11.19]
synonym: "phosphorylase B kinase activity" RELATED [EC:2.7.11.19]
synonym: "phosphorylase kinase (phosphorylating) activity" RELATED [EC:2.7.11.19]
synonym: "phosphorylase kinase, intrinsic catalyst activity" EXACT []
synonym: "STK17" RELATED [EC:2.7.11.19]
xref: EC:2.7.11.19
xref: MetaCyc:2.7.11.19-RXN
```

This is the EC
https://enzyme.expasy.org/EC/2.7.1.19
ATP + D-ribulose 5-phosphate <=> ADP + D-ribulose 1,5-bisphosphate

Multiple issues

 - the xref and definition xref don't match for the regulator
 - the xref and definition xref shouldn't even be on the regulator
 - the xref on the base term seems more justifiable but the chemicals don't precisely match

I don't think we should have EC xrefs on MF regulators

here is another one:

```yaml
id: GO:0016538
name: cyclin-dependent protein serine/threonine kinase regulator activity
namespace: molecular_function
alt_id: GO:0003751
alt_id: GO:0003752
alt_id: GO:0003753
def: "Modulates the activity of a cyclin-dependent protein serine/threonine kinase, enzymes of the protein kinase family that are regulated through association with cyclins and other proteins." [GOC:pr, GOC:rn, PMID:7877684, PMID:9442875]
synonym: "cyclin" BROAD []
synonym: "cyclin-dependent protein kinase regulator activity" BROAD []
synonym: "cyclin-dependent protein kinase, intrinsic regulator activity" NARROW []
synonym: "G1/S-specific cyclin" NARROW []
synonym: "G2/M-specific cyclin" NARROW []
xref: EC:2.7.1.-
intersection_of: GO:0003674 ! molecular_function
intersection_of: regulates GO:0004693 ! cyclin-dependent protein serine/threonine kinase activity
```

**Comment by cmungall** [comment]
Looks like this is already in progress #22450

**Comment by pgaudet** [comment]
> Looks like this is already in progress #22450

Not quite - that was just for this term. Any exhaustive list would be great

**Comment by cmungall** [comment]
it's not so bad, only 2 that are xrefs on regulators with logical defs:

`obo-grep.pl -r 'EC:' go-edit.obo | obo-grep.pl -r 'intersection_of: regulates' -`

there are more if we include definition xrefs

`obo-grep.pl -r 'xref: EC:' go-edit.obo | obo-grep.pl -r 'intersection_of: regulates' -`

this is not such a priority but I feel maintenance is simpler if all regulators have standard genus-differentia defs with no repetition of information from the base term

```yaml

[Term]
id: GO:0008597
name: calcium-dependent protein serine/threonine phosphatase regulator activity
namespace: molecular_function
def: "Binds to and modulates of the activity of the enzyme calcium-dependent protein serine/threonine phosphatase." [EC:3.1.3.16, GOC:ai]
synonym: "calcium-dependent protein serine/threonine phosphatase, intrinsic regulator activity" NARROW []
intersection_of: GO:0098772 ! molecular function regulator
intersection_of: regulates GO:0004723 ! calcium-dependent protein serine/threonine phosphatase activity

[Term]
id: GO:0008607
name: phosphorylase kinase regulator activity
namespace: molecular_function
def: "Modulation of the activity of the enzyme phosphorylase kinase." [EC:2.7.11.19]
synonym: "phosphorylase kinase, intrinsic regulator activity" NARROW []
xref: EC:2.7.1.-
intersection_of: GO:0003674 ! molecular_function
intersection_of: regulates GO:0004689 ! phosphorylase kinase activity

[Term]
id: GO:0016538
name: cyclin-dependent protein serine/threonine kinase regulator activity
namespace: molecular_function
alt_id: GO:0003751
alt_id: GO:0003752
alt_id: GO:0003753
def: "Modulates the activity of a cyclin-dependent protein serine/threonine kinase, enzymes of the protein kinase family that are regulated through association with cyclins and other proteins." [GOC:pr, GOC:rn, PMID:7877684, PMID:9442875]
synonym: "cyclin" BROAD []
synonym: "cyclin-dependent protein kinase regulator activity" BROAD []
synonym: "cyclin-dependent protein kinase, intrinsic regulator activity" NARROW []
synonym: "G1/S-specific cyclin" NARROW []
synonym: "G2/M-specific cyclin" NARROW []
xref: EC:2.7.1.-
intersection_of: GO:0003674 ! molecular_function
intersection_of: regulates GO:0004693 ! cyclin-dependent protein serine/threonine kinase activity

[Term]
id: GO:0017020
name: myosin phosphatase regulator activity
namespace: molecular_function
def: "Binds to and modulates of the activity of myosin phosphatase." [EC:3.1.3.16, GOC:ai]
synonym: "myosin phosphatase, intrinsic regulator activity" NARROW []
intersection_of: GO:0098772 ! molecular function regulator
intersection_of: regulates GO:0017018 ! myosin phosphatase activity

[Term]
id: GO:0019909
name: [pyruvate dehydrogenase (lipoamide)] phosphatase regulator activity
namespace: molecular_function
def: "Binds to and modulates of the activity of [pyruvate dehydrogenase (lipoamide)] phosphatase." [EC:3.1.3.43, GOC:ai]
synonym: "[pyruvate dehydrogenase (lipoamide)] phosphatase, intrinsic regulator activity" NARROW []
intersection_of: GO:0098772 ! molecular function regulator
intersection_of: regulates GO:0004741 ! [pyruvate dehydrogenase (lipoamide)] phosphatase activity

[Term]
id: GO:0051336
name: regulation of hydrolase activity
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of hydrolase activity, the catalysis of the hydrolysis of various bonds, e.g. C-O, C-N, C-C, phosphoric anhydride bonds, etc. Hydrolase is the systematic name for any enzyme of EC class 3." [EC:3.-.-.-, GOC:ai]
synonym: "hydrolase regulator" EXACT []
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0016787 ! hydrolase activity

[Term]
id: GO:0051338
name: regulation of transferase activity
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of transferase activity, the catalysis of the transfer of a group, e.g. a methyl group, glycosyl group, acyl group, phosphorus-containing, or other groups, from one compound (generally regarded as the donor) to another compound (generally regarded as the acceptor). Transferase is the systematic name for any enzyme of EC class 2." [EC:2.-.-.-, GOC:ai]
comment: This term is useful for grouping, but is too general for manual annotation. Please use a child term instead.
subset: gocheck_do_not_manually_annotate
synonym: "transferase regulator" EXACT []
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0016740 ! transferase activity

[Term]
id: GO:0051339
name: regulation of lyase activity
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of lyase activity, the catalysis of the cleavage of C-C, C-O, C-N and other bonds by other means than by hydrolysis or oxidation, or conversely adding a group to a double bond. They differ from other enzymes in that two substrates are involved in one reaction direction, but only one in the other direction. When acting on the single substrate, a molecule is eliminated and this generates either a new double bond or a new ring." [EC:4.-.-.-, GOC:ai]
synonym: "lyase regulator" EXACT []
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0016829 ! lyase activity

[Term]
id: GO:0051340
name: regulation of ligase activity
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of ligase activity, the catalysis of the ligation of two substances with concomitant breaking of a diphosphate linkage, usually in a nucleoside triphosphate. Ligase is the systematic name for any enzyme of EC class 6." [EC:6.-.-.-, GOC:ai]
synonym: "ligase regulator" EXACT []
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0016874 ! ligase activity

[Term]
id: GO:0051341
name: regulation of oxidoreductase activity
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of oxidoreductase activity, the catalysis of an oxidation-reduction (redox) reaction, a reversible chemical reaction in which the oxidation state of an atom or atoms within a molecule is altered. One substrate acts as a hydrogen or electron donor and becomes oxidized, while the other acts as hydrogen or electron acceptor and becomes reduced." [EC:1.-.-.-, GOC:ai]
synonym: "oxidoreductase regulator" EXACT []
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0016491 ! oxidoreductase activity

[Term]
id: GO:0051342
name: regulation of cyclic-nucleotide phosphodiesterase activity
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of cyclic nucleotide phosphodiesterase activity, the catalysis of the reaction: nucleotide 3',5'-cyclic phosphate + H2O = nucleotide 5'-phosphate." [EC:3.1.4.17, GOC:ai, GOC:tb]
synonym: "3',5' cyclic nucleotide phosphodiesterase regulator" EXACT []
synonym: "3',5'-cyclic-AMP phosphodiesterase regulator" NARROW []
synonym: "cAMP phosphodiesterase regulator" NARROW []
synonym: "phosphodiesterase regulator" RELATED []
synonym: "regulation of 3',5' cyclic nucleotide phosphodiesterase activity" EXACT []
synonym: "regulation of 3',5'-cyclic-AMP phosphodiesterase activity" NARROW []
synonym: "regulation of cAMP phosphodiesterase activity" NARROW []
synonym: "regulation of cGMP phosphodiesterase activity" NARROW [GOC:tb]
synonym: "regulation of cyclic nucleotide phosphodiesterase activity" EXACT [GOC:tb]
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0004112 ! cyclic-nucleotide phosphodiesterase activity

[Term]
id: GO:0051421
name: regulation of endo-1,4-beta-xylanase activity
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of endo-(1->4)-beta-xylanase activity, the catalysis of the endohydrolysis of (1->4)-beta-D-xylosidic linkages in xylans." [EC:3.2.1.8, GOC:ai]
synonym: "endo-1,4-beta-xylanase regulator" RELATED []
synonym: "xylanase regulator" RELATED []
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0031176 ! endo-1,4-beta-xylanase activity

[Term]
id: GO:0051972
name: regulation of telomerase activity
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of telomerase activity, the catalysis of the reaction: deoxynucleoside triphosphate + DNA(n) = diphosphate + DNA(n+1). Telomerases catalyze extension of the 3'- end of a DNA strand by one deoxynucleotide at a time using an internal RNA template that encodes the telomeric repeat sequence." [EC:2.-.-.-, GOC:ai]
synonym: "telomerase regulator" EXACT []
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0003720 ! telomerase activity
relationship: regulates GO:0071897 {http://purl.obolibrary.org/obo/IAO_0000233="https://github.com/geneontology/go-ontology/issues/13926"} ! DNA biosynthetic process

[Term]
id: GO:0060584
name: regulation of prostaglandin-endoperoxide synthase activity
namespace: biological_process
def: "Any process that modulates the rate, frequency or prostaglandin-endoperoxide synthase activity. Prostaglandin-endoperoxide synthase activity is the catalysis of the reaction: arachidonate + donor-H2 + 2 O2 = prostaglandin H2 + acceptor + H2O." [GOC:BHF, GOC:dph, GOC:tb]
synonym: "regulation of (PG)H synthase activity" RELATED [EC:1.14.99.1]
synonym: "regulation of fatty acid cyclooxygenase activity" RELATED [EC:1.14.99.1]
synonym: "regulation of PG synthetase activity" RELATED [EC:1.14.99.1]
synonym: "regulation of prostaglandin synthetase activity" RELATED [EC:1.14.99.1]
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0004666 ! prostaglandin-endoperoxide synthase activity
created_by: dph
creation_date: 2009-05-08T02:08:37Z
```

**Comment by cmungall** [comment]
I spoke to soon. My query made the assumption we had assigned logical definitions to all MF regulators

In fact we have not, so my query missed ones like this:

```yaml
id: GO:0019914
name: cyclin-dependent protein kinase activating kinase regulator activity
namespace: molecular_function
def: "Modulation of the activity of the enzyme cyclin-dependent protein kinase activating kinase." [GOC:ai]
synonym: "cyclin-dependent protein kinase activating kinase, intrinsic regulator activity" NARROW []
xref: EC:2.7.1.-
is_a: GO:0019887 ! protein kinase regulator activity
relationship: regulates GO:0019912 ! cyclin-dependent protein kinase activating kinase activity
```

we should really have a MF regulator DP and logdefs for these

**Comment by cmungall** [comment]
sorry for the stream of consciousness. This should reliably find all EC xrefs on regulators:

```bash
obo-grep.pl -r 'EC:' go-edit.obo | obo-grep.pl -r '(relationship|intersection_of): regulates' -
```

I get 10 on the latest ontology:

```yaml

[Term]
id: GO:0019909
name: [pyruvate dehydrogenase (lipoamide)] phosphatase regulator activity
namespace: molecular_function
def: "Binds to and modulates of the activity of [pyruvate dehydrogenase (lipoamide)] phosphatase." [EC:3.1.3.43, GOC:ai]
synonym: "[pyruvate dehydrogenase (lipoamide)] phosphatase, intrinsic regulator activity" NARROW []
intersection_of: GO:0098772 ! molecular function regulator
intersection_of: regulates GO:0004741 ! [pyruvate dehydrogenase (lipoamide)] phosphatase activity

[Term]
id: GO:0051336
name: regulation of hydrolase activity
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of hydrolase activity, the catalysis of the hydrolysis of various bonds, e.g. C-O, C-N, C-C, phosphoric anhydride bonds, etc. Hydrolase is the systematic name for any enzyme of EC class 3." [EC:3.-.-.-, GOC:ai]
synonym: "hydrolase regulator" EXACT []
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0016787 ! hydrolase activity

[Term]
id: GO:0051338
name: regulation of transferase activity
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of transferase activity, the catalysis of the transfer of a group, e.g. a methyl group, glycosyl group, acyl group, phosphorus-containing, or other groups, from one compound (generally regarded as the donor) to another compound (generally regarded as the acceptor). Transferase is the systematic name for any enzyme of EC class 2." [EC:2.-.-.-, GOC:ai]
comment: This term is useful for grouping, but is too general for manual annotation. Please use a child term instead.
subset: gocheck_do_not_manually_annotate
synonym: "transferase regulator" EXACT []
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0016740 ! transferase activity

[Term]
id: GO:0051339
name: regulation of lyase activity
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of lyase activity, the catalysis of the cleavage of C-C, C-O, C-N and other bonds by other means than by hydrolysis or oxidation, or conversely adding a group to a double bond. They differ from other enzymes in that two substrates are involved in one reaction direction, but only one in the other direction. When acting on the single substrate, a molecule is eliminated and this generates either a new double bond or a new ring." [EC:4.-.-.-, GOC:ai]
synonym: "lyase regulator" EXACT []
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0016829 ! lyase activity

[Term]
id: GO:0051340
name: regulation of ligase activity
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of ligase activity, the catalysis of the ligation of two substances with concomitant breaking of a diphosphate linkage, usually in a nucleoside triphosphate. Ligase is the systematic name for any enzyme of EC class 6." [EC:6.-.-.-, GOC:ai]
synonym: "ligase regulator" EXACT []
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0016874 ! ligase activity

[Term]
id: GO:0051341
name: regulation of oxidoreductase activity
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of oxidoreductase activity, the catalysis of an oxidation-reduction (redox) reaction, a reversible chemical reaction in which the oxidation state of an atom or atoms within a molecule is altered. One substrate acts as a hydrogen or electron donor and becomes oxidized, while the other acts as hydrogen or electron acceptor and becomes reduced." [EC:1.-.-.-, GOC:ai]
synonym: "oxidoreductase regulator" EXACT []
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0016491 ! oxidoreductase activity

[Term]
id: GO:0051342
name: regulation of cyclic-nucleotide phosphodiesterase activity
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of cyclic nucleotide phosphodiesterase activity, the catalysis of the reaction: nucleotide 3',5'-cyclic phosphate + H2O = nucleotide 5'-phosphate." [EC:3.1.4.17, GOC:ai, GOC:tb]
synonym: "3',5' cyclic nucleotide phosphodiesterase regulator" EXACT []
synonym: "3',5'-cyclic-AMP phosphodiesterase regulator" NARROW []
synonym: "cAMP phosphodiesterase regulator" NARROW []
synonym: "phosphodiesterase regulator" RELATED []
synonym: "regulation of 3',5' cyclic nucleotide phosphodiesterase activity" EXACT []
synonym: "regulation of 3',5'-cyclic-AMP phosphodiesterase activity" NARROW []
synonym: "regulation of cAMP phosphodiesterase activity" NARROW []
synonym: "regulation of cGMP phosphodiesterase activity" NARROW [GOC:tb]
synonym: "regulation of cyclic nucleotide phosphodiesterase activity" EXACT [GOC:tb]
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0004112 ! cyclic-nucleotide phosphodiesterase activity

[Term]
id: GO:0051421
name: regulation of endo-1,4-beta-xylanase activity
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of endo-(1->4)-beta-xylanase activity, the catalysis of the endohydrolysis of (1->4)-beta-D-xylosidic linkages in xylans." [EC:3.2.1.8, GOC:ai]
synonym: "endo-1,4-beta-xylanase regulator" RELATED []
synonym: "xylanase regulator" RELATED []
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0031176 ! endo-1,4-beta-xylanase activity

[Term]
id: GO:0051972
name: regulation of telomerase activity
namespace: biological_process
def: "Any process that modulates the frequency, rate or extent of telomerase activity, the catalysis of the reaction: deoxynucleoside triphosphate + DNA(n) = diphosphate + DNA(n+1). Telomerases catalyze extension of the 3'- end of a DNA strand by one deoxynucleotide at a time using an internal RNA template that encodes the telomeric repeat sequence." [EC:2.-.-.-, GOC:ai]
synonym: "telomerase regulator" EXACT []
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0003720 ! telomerase activity
relationship: regulates GO:0071897 {http://purl.obolibrary.org/obo/IAO_0000233="https://github.com/geneontology/go-ontology/issues/13926"} ! DNA biosynthetic process

[Term]
id: GO:0060584
name: regulation of prostaglandin-endoperoxide synthase activity
namespace: biological_process
def: "Any process that modulates the rate, frequency or prostaglandin-endoperoxide synthase activity. Prostaglandin-endoperoxide synthase activity is the catalysis of the reaction: arachidonate + donor-H2 + 2 O2 = prostaglandin H2 + acceptor + H2O." [GOC:BHF, GOC:dph, GOC:tb]
synonym: "regulation of (PG)H synthase activity" RELATED [EC:1.14.99.1]
synonym: "regulation of fatty acid cyclooxygenase activity" RELATED [EC:1.14.99.1]
synonym: "regulation of PG synthetase activity" RELATED [EC:1.14.99.1]
synonym: "regulation of prostaglandin synthetase activity" RELATED [EC:1.14.99.1]
intersection_of: GO:0065007 ! biological regulation
intersection_of: regulates GO:0004666 ! prostaglandin-endoperoxide synthase activity
created_by: dph
creation_date: 2009-05-08T02:08:37Z

```
