### ISSUE TITLE
olfactory pit development property range problem

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#22589]
[olfactory pit development](http://purl.obolibrary.org/obo/GO_0060166) 'results in development of' [nasal cavity](http://purl.obolibrary.org/obo/UBERON_0001707), which doesn't work because 'nasal cavity' is immaterial. However there is a term [olfactory pit](http://purl.obolibrary.org/obo/UBERON_0005870) which is a material entity.

@pgaudet @cmungall can I change this logical definition to refer to [olfactory pit](http://purl.obolibrary.org/obo/UBERON_0005870)?

**Comment by balhoff** [comment]
Actually maybe that won't work, here is the text definition:

> The biological process whose specific outcome is the progression of the olfactory pit from an initial condition to its mature state. This process begins with the formation of the olfactory pit, which is an indentation of the olfactory placode, and ends when the pits hollows out to form the nasopharynx.

[nasopharynx](http://purl.obolibrary.org/obo/UBERON_0001728) could work though.

**Comment by balhoff** [comment]
@cmungall what do you think about broadening the range of [results in developmental progression of](http://purl.obolibrary.org/obo/RO_0002295)? It is currently [connected anatomical structure](http://purl.obolibrary.org/obo/CARO_0000003). This also causes a problem for a few other terms, such as [subarachnoid space development](http://purl.obolibrary.org/obo/GO_1903374). Maybe the range could just be [anatomical entity](http://purl.obolibrary.org/obo/CARO_0000000)?

**Comment by cmungall** [comment]
in this case the logical def is just wrong

```yaml
id: GO:0060166
name: olfactory pit development
namespace: biological_process
def: "The biological process whose specific outcome is the progression of the olfactory pit from an initial condition to its mature state. This process begins with the formation of the olfactory pit, which is an indentation of the olfactory placode, and ends when the pits hollows out to form the nasopharynx." [GOC:dph, ISBN:0124020607]
is_a: GO:0032502 ! developmental process
is_a: GO:0048856 ! anatomical structure development
intersection_of: GO:0048856 ! anatomical structure development
intersection_of: results_in_development_of UBERON:0001707 ! nasal cavity
relationship: part_of GO:0043584 ! nose development
```

should use this - and in fact it was seeded from GO!

```yaml
id: UBERON:0005870
name: olfactory pit
def: "An indentation of the olfactory placode which ends when the pits hollows out to form the nasopharynx[GO]." [GO:0060166, Wikipedia:Nasal_pit]
```

I think GO and uberon should use the same strings throughout

I'm not opposed to relaxing the range but let's see if it's really necessary. I suspect we will either want to change either uberon placement or uberon term

for sure cavities and spaces form during development but I think the biological process is best construed as a structure.
