### ISSUE TITLE
chorion micropyle formation - clarify if this is applicable to vertebrates, insects, or both

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#22603]
We have ZFIN annotations to 

http://amigo.geneontology.org/amigo/term/GO:0046844

```yaml
id: GO:0046844
name: chorion micropyle formation
namespace: biological_process
def: "Establishment of the micropyle, a single cone-shaped specialization of the chorion that allows sperm entry into the egg prior to fertilization." [ISBN:0879694238]
is_a: GO:0003006 ! developmental process involved in reproduction
is_a: GO:0032502 ! developmental process
is_a: GO:0048646 ! anatomical structure formation involved in morphogenesis
intersection_of: GO:0048646 ! anatomical structure formation involved in morphogenesis
intersection_of: results_in_formation_of GO:0070825 ! micropyle
relationship: part_of GO:0007306 ! eggshell chorion assembly
```

But these should be flagged as taxon constraints (aside: where are we tracking these?)

The reasons are nuanced and there is a lot of confusion in GO with terms like eggshell/chorion/follicle:

![image](https://user-images.githubusercontent.com/50745/146815432-c7c06dc0-91c2-4e3e-9300-9b66b8560c94.png)

@gouttegd from FlyBase and @paolaroncaglia are working on the underlying CL terms

 * https://github.com/obophenotype/cell-ontology/issues/589
 * https://github.com/obophenotype/uberon/issues/1524

**Comment by pgaudet** [comment]
Is this a question for  ZFIN folks? @sramachand @doughowe

**Comment by cmungall** [comment]
I had assumed chorionic micropyle referred to the insect structure, exemplified by the FBbt term:

https://www.ebi.ac.uk/ols/ontologies/zfa/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FZFA_0000329

The definition in GO referring to cone-shaped morphology seems particular:
https://pubmed.ncbi.nlm.nih.gov/32829690/#:~:text=The%20micropyle%20is%20a%20cone,the%20micropyle%20are%20remarkably%20complex.

In fact the def dbxref for the GO term is https://www.abebooks.com/9780879694234/Development-Drosophila-Melanogaster-Volume-Set-0879694238/plp (aside: I really wish when we had made taxonomic scope more explicit at time of term creation)

The teleost structure seems analogous:
https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007408

_Without a recognizable acrosome reaction, sperm entry in teleosts relies entirely upon a specialized funnel-like structure, the micropyle, in the chorion, an acellular coat of the egg [4–6]. Morphological and physiological studies of the micropyle in a variety of different teleost species suggest that channel formation results from the transformation of a special micropylar cell in mid-oogenesis [7–12]. The micropylar cell is morphologically distinct from other follicle cells surrounding the oocyte. Positioned over the oocyte animal pole, the micropylar cell is bigger in size and appears like an inverted cone in shape, in contrast to the flattened appearance of follicle cells, sometimes called ‘mushroom’-like [11–13]. The unique shape of the micropylar cell is gradually achieved during oogenesis. A cytoplasmic extension from the micropylar cell expands and extends through the developing vitelline envelope, till the extension tip contacts the oocyte membrane, as the vitelline envelope grows and perforation proceeds, the cytoplasmic extension becomes slim and long [14]. Finally, the micropylar cell degenerates, leaving a narrow canal called the ‘micropyle’ between the chorion and the egg [15, 16]._

**Comment by cmungall** [comment]
Also, the term "chorion-containing eggshell" in GO is odd. 

```yaml
id: GO:0007304
name: chorion-containing eggshell formation
namespace: biological_process
def: "The construction of a chorion-containing eggshell. An example of this is found in Drosophila melanogaster." [GOC:mah, GOC:mtg_sensu]
synonym: "eggshell formation" BROAD []
is_a: GO:0030703 ! eggshell formation
intersection_of: GO:0048646 ! anatomical structure formation involved in morphogenesis
intersection_of: results_in_formation_of UBERON:0005307 ! chorion-containing eggshell
relationship: part_of GO:0030707 ! ovarian follicle cell development
```

(the uberon term simply mirrors the GO term)

it looks like an attempt to make a term for insect eggshells, but having an undefined "chorion" as the differentia doesn't really help here as the analogome of chorion is large. In amniotes it's the outermost extraembryonic membrane. In teleosts the chorion *is* the eggshell, so the taxonomic scope of GO:0007304 is very unclear
