### ISSUE TITLE
NTR: 1,3-beta-D-glucan synthase, subtypes for branched and linear forms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22637]
Please provide as much information as you can: 

* **Suggested term label:**

1 branched 1,3-beta-D-glucan synthase activity
2 linear  1,3-beta-D-glucan synthase activity

* **Definition (free text)**

I am not sure how definitions are formulated for  branched and linear, but I would like to differentiate these specificities.

It seems to make sense to differentiate at the MF level otherwise  we would need lots and lots of BPs under different processes

* **Reference, in format PMID:#######**

We can use this paper as a reference:

In all the studied fungi, the catalytic subunit of the β(1,3)-D-glucan synthase (GS), the glycosyltransferase in charge of the β(1,3)-D-glucan synthesis, is constituted by the family of integral membrane proteins Bgs/Fks [19,21,22]. S. pombe contains four essential GS catalytic subunits: Bgs1 synthesizes the linear β(1,3)-D-glucan of the primary septum [19] and is required for septum ingression [19,23–25]; Bgs2 is essential for spore wall matura- tion [26,27]; Bgs3 is essential, although its function remains unknown [28]; and Bgs4 is the only subunit that has been shown to form part of the GS enzyme. It synthesizes the branched β(1,3)-D-glucan and is responsible for most GS activity [19,29]. The branched β(1,3)-D-glucan produced by Bgs4 is vital for maintaining cell shape and septum forma- tion and completion. Differently from Bgs1 and Bgs3, the function of Bgs4 is essential for cell integrity, and thus, Bgs4 depletion causes cell lysis and cytoplasm leakage in the growing poles and mainly in the medial region at the onset of septum degradation and cell separation [30].

PMID:34959732

* **Gene product name and ID to be annotated to this term**

S. pombe bgs4 - branched
S. pombe bgs1 - linear

* **Parent term(s)**

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by cmungall** [comment]
@amorgat is there any precedent for making these subtypes in RHEA?

I note that in CHEBI (1->3)-beta-D-glucan https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:37671  there are subtypes for n=5 and n=15, but no subtypes for branched vs linear.

**Comment by deustp01** [comment]
A possible analog is synthesis of glycogen in animal cells. Two basic steps are involved, the synthesis of a linear glucose polymer, described by GO:0004373 and RHEA:18549, and a reaction that transfers an oligosaccharide from the end of that linear polymer to form a branch, described by  GO:0003844 1,4-alpha-glucan branching enzyme activity. A search for GO:0003844 in RHEA returns no hits. Maybe this is a place to start?

**Comment by cmungall** [comment]
Good example, thanks Peter.

So indeed, there is no Rhea for

```yaml
id: GO:0003844
name: 1,4-alpha-glucan branching enzyme activity
namespace: molecular_function
def: "Catalysis of the transfer of a segment of a (1->4)-alpha-D-glucan chain to a primary hydroxyl group in a similar glucan chain." [EC:2.4.1.18]
synonym: "1,4-alpha-D-glucan:1,4-alpha-D-glucan 6-alpha-D-(1,4-alpha-D-glucano)-transferase activity" EXACT []
synonym: "1,4-glucan-6-(1,4-glucano)-transferase activity" EXACT []
synonym: "alpha-1,4-glucan:alpha-1,4-glucan-6-glycosyltransferase activity" RELATED [EC:2.4.1.18]
synonym: "alpha-glucan-branching glycosyltransferase activity" RELATED [EC:2.4.1.18]
synonym: "amylo-(1,4 to 1,6)transglucosidase activity" RELATED [EC:2.4.1.18]
synonym: "amylo-(1,4->1,6)-transglycosylase activity" RELATED [EC:2.4.1.18]
synonym: "amylose isomerase activity" RELATED [EC:2.4.1.18]
synonym: "branching enzyme activity" RELATED [EC:2.4.1.18]
synonym: "branching glycosyltransferase activity" RELATED [EC:2.4.1.18]
synonym: "enzymatic branching factor" RELATED [EC:2.4.1.18]
synonym: "enzyme Q" RELATED [EC:2.4.1.18]
synonym: "glucosan transglycosylase activity" RELATED [EC:2.4.1.18]
synonym: "glycogen branching enzyme activity" RELATED [EC:2.4.1.18]
synonym: "plant branching enzyme" RELATED [EC:2.4.1.18]
synonym: "Q-enzyme" RELATED [EC:2.4.1.18]
synonym: "starch branching enzyme" RELATED [EC:2.4.1.18]
xref: EC:2.4.1.18
xref: MetaCyc:GLYCOGEN-BRANCH-RXN
is_a: GO:0016758 ! hexosyltransferase activity
```

The human gene responsible is:

https://www.uniprot.org/uniprot/Q04446

Doesn't have a Rhea - curious if it would be Rhea policy to grant one here

(none of this should block granting of a GO term for the pombe genes, but medium term we should make sure we have clear design patterns for these subtypes)
