### ISSUE TITLE
remove link between reproductive structure development and uberon reproductive structure

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#23445]
```yaml
id: GO:0048608
name: reproductive structure development
namespace: biological_process
def: "The reproductive developmental process whose specific outcome is the progression of somatic structures that will be used in the process of creating new individuals from one or more parents, from their formation to the mature structures." [GOC:dph, GOC:isa_complete, GOC:jid]
is_a: GO:0003006 ! developmental process involved in reproduction
is_a: GO:0048856 ! anatomical structure development
intersection_of: GO:0048856 ! anatomical structure development
intersection_of: results_in_development_of UBERON:0005156 ! reproductive structure
```

The implicit term referenced by GO is much more general than the uberon structure, which is *multicellular* (the uberon one is also artifically restricted to eumetazoa due to a mistake here https://github.com/obophenotype/uberon/issues/2514, but regardless of this mistake, the GO term is more general)

let's just remove the logical definition

I'm not totally convinced such a general term is useful in GO it should at least have a do-not-annotate on it
