### ISSUE TITLE
Taxon constraint: neurotransmitter-related

### ISSUE THREAD

**Issue by AndreaAuchincloss** [geneontology/go-ontology#25206]
We ran across a Chlamydomonas reinhardtii protein (A0A2K3CPE0) that has 2 GO terms related to neurotransmission (GO:0007268, GO:0030594, I cannot dispute them using Protein2GO). Chlamy is a unicellular green algae, so these terms are incorrect. 

GO term ID label:GO:0007268
never in taxon: Viridiplantae

For GO:0030594 I don't know where the hierarchy problem lies exactly, although I note the high level parent term synapse (GO:0045202) should not be permitted in Viridiplantae. Synapse is supposed to only by in Metazoa, but its children are in this algal entry. Can you explicitly add an exclusion please:

GO term ID label: GO:0045202
never in taxon: Viridiplantae

Thank you, Andrea

**Comment by ValWood** [comment]
ancestor "synaptic signalling" has "never in s. pombe"
I will change to  "only in metazoa"
and add also to  GO:0030594  neurotransmitter receptor activity

**Comment by ValWood** [comment]
@balhoff 
I did the additiona  in the Git editor. Except that I couldn't  find how to search on a file  to find the existing
synaptic signaling "never in s. pombe"
so I edited this manually  and checked in the tsv file while on branch issue-31-03-23
I'm not sure that this was the right thing to do  so if there is a problem, this might be it.

**Comment by balhoff** [comment]
@ValWood I looked at the never_in_taxon file, and I guess you found the entry. I did open a PR to replace a space with a tab: #25215

**Comment by cmungall** [comment]
"synaptic signaling" should already inherit a metazoan TC:

via OAK:

```
go taxon-constraints "synaptic signaling"
id: GO:0099536
label: synaptic signaling
description: 'Term GO:0099536 "synaptic signaling" is ONLY found in
NCBITaxon:33208
  "Metazoa" (NOT asserted: original term = GO:0045202 "synapse"); is NEVER
found in
  NCBITaxon:4751 "Fungi" IS asserted'
only_in:
- subject: GO:0045202
  predicate: RO:0002160
  asserted: false
  redundant: false
  taxon:
    id: NCBITaxon:33208
    label: Metazoa
  via_terms:
  - id: GO:0045202
    label: synapse
```

also showing redundant:

```
go taxon-constraints "synaptic signaling" --include-redundant
id: GO:0099536
label: synaptic signaling
description: 'Term GO:0099536 "synaptic signaling" is ONLY found in
NCBITaxon:33208
  "Metazoa" (NOT asserted: original term = GO:0045202 "synapse"); is NEVER
found in
  NCBITaxon:4751 "Fungi" IS asserted'
only_in:
- subject: GO:0045202
  predicate: RO:0002160
  asserted: false
  redundant: false
  taxon:
    id: NCBITaxon:33208
    label: Metazoa
  via_terms:
  - id: GO:0045202
    label: synapse
never_in:
- subject: GO:0030054
  predicate: RO:0002161
  asserted: false
  redundant: false
  redundant_with_only_in: true
  taxon:
    id: NCBITaxon:4751
    label: Fungi
  via_terms:
  - id: GO:0030054
    label: cell junction
- subject: GO:0099536
  predicate: RO:0002161
  asserted: true
  redundant: true
  redundant_with_only_in: true
  taxon:
    id: NCBITaxon:4895
    label: Schizosaccharomyces
  redundant_with:
  - subject: GO:0030054
    taxon:
      id: NCBITaxon:4751
      label: Fungi
    via_terms:
    - id: GO:0030054
      label: cell junction
  via_terms:
  - id: GO:0099536
    label: synaptic signaling
```

the activity one is unique but I think this is just highlighting a
different issue - CHEBI roles are terrible for axiomatizing things like
neurotransmission - we have a GO process, we should use it!!!
