### ISSUE TITLE
NTR/New def: ionotropic taste receptor activities

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#25533]
Currently we have taste receptor activities for GPCRs but not ligand-gated ion channels:

GO:0008527	taste receptor activity
		GO:0090681	GPCR taste receptor activity
			 GO:0090683	GPCR sweet taste receptor activity
			 GO:0090682	GPCR bitter taste receptor activity
			 

Could we create the sister terms for sweet and bitter ionotropic taste receptor activities, a parent term ionotropic taste receptor activity and redefine salty taste receptor activity?

*NTR: ionotropic bitter taste receptor activity*
**Def:** Enables the transmembrane transfer of an ion by a channel that opens when a specific  bitter compound has been bound by the channel complex or one of its constituent parts.

**To annotate** FBgn0041235 Gr59c (PMID:21262465)
			 	
*NTR:ionotropic sweet taste receptor activity*
**Def:** Enables the transmembrane transfer of an ion by a channel that opens when a specific  soluble sweet compound has been bound by the channel complex or one of its constituent parts.
**To annotate** FBgn0045479 Gr64a (PMID:24474785)

*Redefine:* GO:0033039 salty taste receptor activity 
From Molecular and Cellular Mechanisms of Salt Taste  PMID:36332657 it appears that salty taste is only mediated by ion channels. Therefore, could the term 

There is only one EXP annotation to GO:0033039 salty taste receptor activity (Ir76b, FBgn0036937), the rest are IEAs to Drosophila orthologs from EnsemblMetazoa propagation. 

Could we **relabel** this term 
GO:0033039 salty taste receptor activity  > ionotropic salty taste receptor activity

**New Def** Enables the transmembrane transfer of an ion by a channel that opens when a soluble salty compound has been bound by the channel complex or one of its constituent parts.

*Parentage for these new terms:*
ionotropic bitter taste receptor activity 
ionotropic sweet taste receptor activity 
ionotropic salty taste receptor activity

is_a GO:0015276 ligand-gated monoatomic ion channel activity 
is_a GO:0090681	ionotropic taste receptor activity

**Other info** 
Review of D.mel taste receptors PMID:36828965

**Comment by hattrill** [comment]
related to request  #25525

**Comment by edwong57** [comment]
@hattrill Do you already have a definition and PMID ref for the new  parent term 'ionotropic taste receptor activity'? I tried looking at Review of D.mel taste receptors PMID:36828965, but I got a 404 error.

**Comment by hattrill** [comment]
Yes, I think that the definition could be:
"Enables the transmembrane transfer of an ion by a channel that opens when a soluble compound has been bound by the channel complex or one of its constituent parts."

PMID:36828965 should be ok for a ref, I will email the pdf to you.

**Comment by cmungall** [comment]
reopening as the new terms are not yet fully connected:

```yaml
[Term]
id: GO:0170022
name: ionotropic bitter taste receptor activity
namespace: molecular_function
def: "Enables the transmembrane transfer of an ion by a channel that opens when a specific bitter compound has been bound by the channel complex or one of its constituent parts." [PMID:21262465]
is_a: GO:0170021 ! ionotropic taste receptor activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25533" xsd:anyURI
created_by: ew
creation_date: 2023-07-03T19:22:08Z

[Term]
id: GO:0170023
name: ionotropic sweet taste receptor activity
namespace: molecular_function
def: "Enables the transmembrane transfer of an ion by a channel that opens when a specific soluble sweet compound has been bound by the channel complex or one of its constituent parts." [PMID:24474785]
is_a: GO:0170021 ! ionotropic taste receptor activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25533" xsd:anyURI
created_by: ew
creation_date: 2023-07-03T19:24:28Z
```
