### ISSUE TITLE
the comment on "obsolete alpha-pinene monooxygenase activity" contradicts consider tag

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#27214]
```yaml
id: GO:0018595
name: obsolete alpha-pinene monooxygenase activity
namespace: molecular_function
def: "OBSOLETE. Catalysis of the reaction: alpha-pinene + O2 + 2 H+ + 2 e- = H2O + pinocarveol." [UM-BBD_reactionID:r0716]
comment: This term was obsoleted because it represents the same reaction as alpha-pinene monooxygenase [NADH] activity ; GO:0018634.
xref: UM-BBD_reactionID:r0716
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26207" xsd:anyURI
is_obsolete: true
consider: GO:0046249
```

If we are to believe the comment then there should be a `replaced_by` to GO:0018634 ! alpha-pinene monooxygenase [NADH] activity

Instead there is a consider to GO:0046249 ! alpha-pinene catabolic process

obsoleted in #26207 - but the majority of the discussion here is on dehydrogenase and lyase
