### ISSUE TITLE
ammonia monooxygenase activity definition is hyper-specific

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#27210]
The definition of ammonia monooxygenase activity is wildly specific:

```yaml
id: GO:0018597
name: ammonia monooxygenase activity
namespace: molecular_function
def: "Catalysis of the oxidation of alkanes (up to C8) to alcohols and alkenes (up to C5) to epoxides and alcohols in the presence of ammonium ions." [PMID:16347810]
xref: EC:1.14.99.39
xref: RHEA:27341
xref: UM-BBD_enzymeID:e0061
is_a: GO:0004497 ! monooxygenase activity
is_a: GO:0016705 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen
```

I guess it is true that a paper from last century characterized this enzyme in one species has having this very specific functionality (https://pubmed.ncbi.nlm.nih.gov/16347810/) it's crazy to generalize this to the definition of the first part of the nitrification pathway.

This definition exemplifies two different bad practices

1. The use of a PMID for an *annotation* as a general *term definition*. This is common in GO. This is one example of why this is bad practice
2. Using an ad-hoc reference rather than canonical sources for leaf node MFs (RHEA > EC > GO)
