### ISSUE TITLE
make the start and end of nitrate assimilation clearer

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#27216]
```yaml
id: GO:0042128
name: nitrate assimilation
namespace: biological_process
def: "The nitrogen metabolic process that encompasses the uptake of nitrate from the environment and reduction to ammonia, and results in the incorporation of nitrogen derived from nitrate into cellular substances." [GOC:das, GOC:mah, PMID:10542156, PMID:8122899]
synonym: "assimilatory nitrate reduction" EXACT []
xref: MetaCyc:PWY-381
is_a: GO:0042126 ! nitrate metabolic process
is_a: GO:0071941 ! nitrogen cycle metabolic process
```

The definition is not clear wrt starts and ends. 

Databases like KEGG and MetaCyc have a clear concept of assimilatory nitrate reduction, which is two steps to get from nitrate to ammonium via nitrite:

<img width="966" alt="image" src="https://github.com/geneontology/go-ontology/assets/50745/af7154c1-bded-4be5-a95e-57d2f867886c">

The GO process appears to include steps upstream. But how far upstream?

Note that we are getting a lot of annotations from
https://www.uniprot.org/keywords/KW-0534 (Nitrate assimilation)

_Protein involved in the uptake, from the environment, of nitrates, inorganic or organic salts and esters of nitric acid. This includes the uptake and transport into cells by nitrate transporters, with the sequential reduction to nitrite and ammonium, catalyzed by the enzymes nitrate reductase and nitrite reductase, respectively._

This is more explicitly broad and specifically includes transporters, e.g
https://www.uniprot.org/uniprotkb/P37758/entry

In general we should align our definitions with KWs we are mapped to otherwise we will have TPVs

I recommend

1. Adding a textual and logical starts_with to `nitrate transmembrane transporter activity` (GO:0015112)
2. Making it clear the pathway ends with ammonia (add an ends-with?)
3. Changing "assimilatory nitrate reduction" EXACT to NARROW; OR:
4. [optional] creating a sub-process "assimilatory nitrate reduction" which is nitrate->nitrite->ammonium (in which case we want to coordinate IPR2GO and PAINT so we can populate this)
