### ISSUE TITLE
The concept of nitrogen fixation in GO is unclear and unlinked to the underlying nitrogenase activities

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#27215]
```yaml
id: GO:0009399
name: nitrogen fixation
namespace: biological_process
def: "The process in which nitrogen is taken from its relatively inert molecular form (N2) in the atmosphere and converted into nitrogen compounds useful for other chemical processes, such as ammonia, nitrate and nitrogen dioxide." [Wikipedia:Nitrogen_fixation]
xref: MetaCyc:N2FIX-PWY
xref: Wikipedia:Nitrogen_fixation
is_a: GO:0071941 ! nitrogen cycle metabolic process
```

This is an OK definition for Wikipedia but it's not a clear definition for GO. What is the end of the process precisely? Given that the direct output is always ammonia, does this term do any more useful work than having a general reaction term to represent N₂ to NH₄⁺?

Other databases do treat this as a "pathway", but as a clear single-step reaction or grouping of reactions:

https://biocyc.org/META/NEW-IMAGE?type=NIL&object=N2FIX-PWY

<img width="621" alt="image" src="https://github.com/geneontology/go-ontology/assets/50745/b19bec44-cf1b-41a1-8491-31dda0f76c84">

https://www.genome.jp/module/M00175

<img width="566" alt="image" src="https://github.com/geneontology/go-ontology/assets/50745/481a6eaf-3208-45ea-90cb-eea66f53cf4a">

The actual reaction is catalyzed by a complex, two different mechanisms:

Represented by two different MFs.

* [] BFO:0000003 ! occurrent
    * [i] BFO:0000015 ! process
        * [i] GO:0003674 ! molecular_function
            * [i] GO:0003824 ! catalytic activity
                * [i] GO:0016491 ! oxidoreductase activity
                    * [i] GO:0016730 ! oxidoreductase activity, acting on iron-sulfur proteins as donors
                        * [i] GO:0016732 ! oxidoreductase activity, acting on iron-sulfur proteins as donors, dinitrogen as acceptor
                            * [i] **GO:0016163 ! nitrogenase activity**
                    * [i] GO:0016737 ! oxidoreductase activity, acting on reduced flavodoxin as donor
                        * [i] GO:0016738 ! oxidoreductase activity, acting on reduced flavodoxin as donor, dinitrogen as acceptor
                            * [i] **GO:0050142 ! nitrogenase (flavodoxin) activity**

Note these MFs are unlinked to the BP, in either direction.

It looks like we are getting a lot of annotations from the KW "nitrogen fixation" https://www.uniprot.org/keywords/KW-0535

This includes members of the 2-component regulatory system NtrB/NtrC which are involved in nitrogen sensing and regulate a number of downstream genes, including nitrogenases
https://www.uniprot.org/uniprotkb/P0AFB5/entry

So it looks like some people are interpreting "nitrogen fixation" very broadly to mean "something or other to do with nitrogen fixation, maybe multiple steps upstream". I don't think this is useful.

Some options are:

1. Make NF a strictly one-step process consistent with KEGG and MetaCyc. Give it a clear endpoint of ammonia. Add part-ofs from the 2 MFs. This essentially makes the BP a grouping class for the MFs. Remove the KW2GO link as unreliable, or block annotations coming this way, or fix these upstream
2. Obsolete NF and force annotators to choose one of the two MFs. (major disadvantage: GO has no concept for the well-known and massively important concept of NF)
3. Create a grouping term for the two nitrogenase activities in MF. Obsolete BP-NF and make "NF" an exact synonym of the grouping MF
4. Keep the existing term but relabel it and redefine it to explicitly be the fuzzy somewhat useless and confusing grouping that is currently is. Call it something like "NF or regulation of NF". We still want MF2BP part-ofs.

I think 1 is best. Note if we block the dodgy KW2GO we still get perfectly good annotations from Interpro2GO, and we can also get them from MF2BP links. The advantage also of 1 is that there is a clear direction.
