### ISSUE TITLE
Improve definition of denitrification pathway and add parts

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#27221]
```yaml
id: GO:0019333
name: denitrification pathway
namespace: biological_process
def: "The reduction of nitrate to dinitrogen by four reactions; each intermediate is transformed to the next lower oxidation state; also part of cellular bioenergetics; the nitrogen compounds can serve as terminal acceptors for electron transport phosphorylation in place of oxygen." [MetaCyc:DENITRIFICATION-PWY]
xref: MetaCyc:DENITRIFICATION-PWY
is_a: GO:0071941 ! nitrogen cycle metabolic process
```

The definition is not wrong but it doesn't conform to GO style; e.g. the use of semi-colons; the use of terms such as "cellular bioenergetics" that are not referenced elsewhere (seems like an axiom missing here). It's a little indirect about specificity, IMO it would be better to name the reactions.

We should add has-part relationships, and starts and ends, e.g

```yaml
relationship: starts_with GO:0008940 ! nitrate reductase activity
relationship: ends_with GO:0050304 ! nitrous-oxide reductase activity
```

I also want to acknowledge the role unipathway plays in making sure that this term is not underpopulated in microbes (see for example all [NosZ](https://www.uniprot.org/uniprotkb/Q51705/entry) in uniprot). It's a shame this is no longer supported.

The unipathway ontology makes the steps very clear:

* [] UPa:UPA00045 ! nitrogen metabolism
    * [i] **UPa:UPA00654 ! nitrate reduction**
        * [i] UPa:UPA00653 ! nitrate reduction (assimilation)
        * [i] UPa:UPA00652 ! nitrate reduction (denitrification)
            * [i] UPa:UPA00638 ! nitric oxide reduction
            * [p] UPa:ULS00347 ! dinitrogen from nitrate
                * [p] UPa:UER00709 ! dinitrogen from nitrate: step 4/4
                    * [p] UPa:UCR02804 ! H(2)O + dinitrogen + 2 ferricytochrome c = 2 H(+) + 2 ferrocytochrome c + nitrous oxide
                * [p] UPa:UER00708 ! dinitrogen from nitrate: step 3/4
                    * [p] UPa:UCR00294 ! 2 H(+) + 2 ferrocytochrome c + 2 nitric oxide = H(2)O + 2 ferricytochrome c + nitrous oxide
                * [p] UPa:UER00707 ! dinitrogen from nitrate: step 2/4
                    * [p] UPa:UCR00783 ! H(2)O + ferricytochrome c + nitric oxide = H(+) + ferrocytochrome c + nitrite
                * [p] UPa:UER00706 ! dinitrogen from nitrate: step 1/4
                    * [p] UPa:UCR00798 ! H(2)O + acceptor + nitrite = nitrate + reduced acceptor
