### ISSUE TITLE
rename GO:0000010 trans-hexaprenyltranstransferase activity to be consistent with EC primary name

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#27609]
```yaml
id: GO:0000010
name: trans-hexaprenyltranstransferase activity
namespace: molecular_function
alt_id: GO:0036422
def: "Catalysis of the reaction: (2E,6E)-farnesyl diphosphate + 4 isopentenyl diphosphate = 4 diphosphate + all-trans-heptaprenyl diphosphate." [PMID:9708911, RHEA:27794]
synonym: "all-trans-heptaprenyl-diphosphate synthase activity" RELATED [EC:2.5.1.30]
synonym: "HepPP synthase activity" RELATED [EC:2.5.1.30]
synonym: "heptaprenyl diphosphate synthase activity" RELATED []
synonym: "heptaprenyl pyrophosphate synthase activity" RELATED [EC:2.5.1.30]
synonym: "heptaprenyl pyrophosphate synthetase activity" RELATED [EC:2.5.1.30]
xref: EC:2.5.1.30
xref: MetaCyc:TRANS-HEXAPRENYLTRANSTRANSFERASE-RXN
xref: RHEA:27794
is_a: GO:0004659 ! prenyltransferase activity
is_a: GO:0016765 ! transferase activity, transferring alkyl or aryl (other than methyl) groups
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/23472" xsd:anyURI
```

The [EC term](https://enzyme.expasy.org/EC/2.5.1.30) has `heptaprenyl diphosphate synthase` as the primary name, but `trans-hexaprenyltranstransferase` is a synonym (presumably the enzyme can catalyze reactions with prenylchain chains of either length(?)

I think it's more consistent if GO uses `hept-` in the primary label. This is also consistent with the [RHEA](https://www.rhea-db.org/rhea/27794)

<img width="1293" alt="image" src="https://github.com/geneontology/go-ontology/assets/50745/d2eed10d-9cff-410e-a926-ddea6e58f80d">

And not to overload, but a few additional observations:

Is it always clear to curators when to use a more specific form of a reaction as a standin for a general class? Here my understanding is that for medium length prenylchains the enzyme may be interchangeable, but different species may favor different lengths (possibly to do with hydrophobicity of membranes).

Currently we have one experimental annotation to this term (SGD COQ1), from this publication:

https://amigo.geneontology.org/amigo/reference/PMID:9708911

Skimming this it seems dubious to annotate this specificity - the experiment involve heterologous expression of different bacterial prenyl synthases using the promoter for yeast.

This may have been the conclusion of the PAINT curator who chose to go one level up to a chain-length neutral form [prenyltransferase activity](https://amigo.geneontology.org/amigo/term/GO:0004659)

See:
https://amigo.geneontology.org/amigo/gene_product/SGD:S000000207

It does seem that HexPP is the correct form for yeast: https://academic.oup.com/femsle/article/203/2/131/642911

And in fact the chemical used in yeastpathways is the hex form...
https://pathway.yeastgenome.org/YEAST/NEW-IMAGE?type=REACTION&object=RXN3O-9805
But note yeastpathways only commits to the 3-level EC....

And we do have terms for hex-form, this RHEA differs from the one above only in chain length:

https://www.rhea-db.org/rhea/27559

<img width="1241" alt="image" src="https://github.com/geneontology/go-ontology/assets/50745/e9e65d23-d213-47d6-9990-34c64b7f9fd3">

This is not particularly high priority but this term was flagged by an LLM analysis and wanted to park my notes
