### ISSUE TITLE
Aligning pectinesterase with RHEA

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#28753]
```yaml
id: GO:0030599
name: pectinesterase activity
namespace: molecular_function
def: "Catalysis of the reaction: pectin + n H2O = n methanol + pectate." [EC:3.1.1.11]
synonym: "pectase activity" RELATED [EC:3.1.1.11]
synonym: "pectin demethoxylase activity" RELATED [EC:3.1.1.11]
synonym: "pectin methoxylase activity" RELATED [EC:3.1.1.11]
synonym: "pectin methyl esterase activity" RELATED [EC:3.1.1.11]
synonym: "pectin methylesterase activity" EXACT []
synonym: "pectin pectylhydrolase activity" RELATED [EC:3.1.1.11]
synonym: "pectinoesterase activity" RELATED [EC:3.1.1.11]
xref: EC:3.1.1.11
xref: MetaCyc:RXN-19782
xref: RHEA:22380
is_a: GO:0052689 ! carboxylic ester hydrolase activity
```

The GO definition (added in 2002 #727) is a simple definition that aligns with EC and normal biologist usage. It refers to "pectin" and "pectate", structures with related but important biological roles.

In RHEA this is
https://www.rhea-db.org/rhea/22380

<img width="1462" alt="image" src="https://github.com/user-attachments/assets/be8f4a59-b14a-4534-852e-e00eabe8dcdc">

The CHEBI IDs used by RHEA are less recognizable to me, and don't relate to the CHEBI concepts of pectin and pectate:

<img width="1181" alt="image" src="https://github.com/user-attachments/assets/dd3d9694-cf9b-47c3-84f7-34b699269504">

The pedant in me wants to say the relationship between the RHEA and the GO should not be equivalent... but when we look at how the RHEA has been used (presumably by propagating from EC), we get all the right pectinesterases: https://www.uniprot.org/uniprotkb/?query=rhea:22380

A slight complicating factor is that CHEBI has pectin and pectate as a conjugate clique, treating them as an equivalence group for GO purposes - but I think CHEBI is wrong here. see

- https://github.com/ebi-chebi/ChEBI/issues/4475
