### ISSUE TITLE
Proposed changes to cellular anatomical entity from COB meeting

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#28978]
```yaml
id: GO:0110165
name: cellular anatomical entity
namespace: cellular_component
def: "A part of a cellular organism that is either an immaterial entity or a material entity with granularity above the level of a protein complex but below that of an anatomical system. Or, a substance produced by a cellular organism with granularity above the level of a protein complex." [GOC:kmv]
subset: gocheck_do_not_annotate
subset: goslim_pir
is_a: GO:0005575 ! cellular_component
```

Can we remove the "either an immaterial entity or a material entity", everything in GO is material.

I suggest also explicitly ruling out virion components here as well

We also had discussion about the label, some found it to be a little abstract, but alternatives like "subcellular structure" don't sufficiently rule out complexes and virion components.
