### ISSUE TITLE
Taxon constraint: GO:0048489	synaptic vesicle transport	

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#29069]
Please provide as much information as you can: 

* **GO term ID label:**

GO:0048489	synaptic vesicle transport Only in Taxon	2759	Eukaryota

Needs a stricter taxon restriction
https://github.com/geneontology/go-annotation/issues/5036

* **Request to add a taxon constraint:**
* * **only in taxon: **
* * **never in taxon: **

* **Request to remove a taxon constraint:**
Please specify

* **Supporting evidence if available (e.g PMID):**

**Comment by cmungall** [comment]
> GO:0048499 synaptic vesicle membrane organization

@balhoff I think we need to add more taxon property chains, e.g. for RO:0002592 `results in organization of`

**Comment by cmungall** [comment]
> GO:0048489 synaptic vesicle transport

This should be Eumetazoa (animals minus sponge)

Ideally we would not assert this, but it can't be inferred from the current axioms:

```yaml
id: GO:0048489
name: synaptic vesicle transport
namespace: biological_process
alt_id: GO:0016181
def: "The directed movement of synaptic vesicles." [GOC:aruk, GOC:bc, GOC:jid, GOC:lmg, GOC:pr]
subset: goslim_synapse
synonym: "synaptic vesicle fission" RELATED []
synonym: "synaptic vesicle fusion" RELATED []
synonym: "synaptic vesicle trafficking" RELATED [PMID:15217342]
is_a: GO:0009987 ! cellular process
intersection_of: GO:0006810 ! transport
intersection_of: has_primary_input GO:0008021 ! synaptic vesicle
```

We don't want to propagate over has_primary_input since there are inter-organism has-primary-inputs.

But I think the real issue here is that `synaptic vesicle transport` is woefully underdescribed and under-axiomatized here. If we had more complete part-ofs and starts and ends. I'll make another issue for this. For now it may be expedient to assert the TC and remove it later when it becomes redundant after we improve the GO term.
