### ISSUE TITLE
Add more information to synaptic vesicle transport

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#29071]
Current synaptic vesicle transport:

```yaml
id: GO:0048489
name: synaptic vesicle transport
namespace: biological_process
alt_id: GO:0016181
def: "The directed movement of synaptic vesicles." [GOC:aruk, GOC:bc, GOC:jid, GOC:lmg, GOC:pr]
subset: goslim_synapse
synonym: "synaptic vesicle fission" RELATED []
synonym: "synaptic vesicle fusion" RELATED []
synonym: "synaptic vesicle trafficking" RELATED [PMID:15217342]
is_a: GO:0009987 ! cellular process
intersection_of: GO:0006810 ! transport
intersection_of: has_primary_input GO:0008021 ! synaptic vesicle
```

The description is very generic and doesn't give much context.

There is a single is-a child and a single part-of child - two red flags

Here is a subtree - note the overall graph of GO in this area is very hairbally:

* [] GO:0006810 ! transport
    * [i] **GO:0048489 ! synaptic vesicle transport**
        * [i] GO:0099514 ! synaptic vesicle cytoskeletal transport
            * [i] GO:0099517 ! synaptic vesicle transport along microtubule
                * [i] GO:0048491 ! retrograde synaptic vesicle transport
                * [i] GO:0048490 ! anterograde synaptic vesicle transport
            * [i] GO:0099506 ! synaptic vesicle transport along actin filament
        * [p] GO:0070142 ! synaptic vesicle budding
            * [i] GO:0016185 ! synaptic vesicle budding from presynaptic endocytic zone membrane *(ALSO po cycle)*
                * [p] GO:0016183 ! synaptic vesicle coating
            * [i] GO:0016182 ! synaptic vesicle budding from endosome *(ALSO po cycle)*

What is the non-cytoskeleton form of transport and why does it not warrant mention? What are the other parts of the transport other than budding and why don't they warrant mention? And is budding really a part of transport?

confusing things, we have the cycle classified as a type of transport

```yaml
id: GO:0099504
name: synaptic vesicle cycle
namespace: biological_process
def: "A biological process in which synaptic vesicles are loaded with neurotransmitters, move to the active zone, exocytose and are then recycled via endocytosis, ultimately leading to reloading with neurotransmitters." [GOC:aruk, GOC:bc, PMID:15217342]
subset: goslim_synapse
is_a: GO:0016192 ! vesicle-mediated transport
relationship: occurs_in GO:0098793 ! presynapse
```

this is true in some sense in that the cycle involves things moving around... and independent of vesicle transport, neurotransmitters are actively transported into the vesicle... but does transport even mean anything any more here?

But at least the cycle term has clear parts

<img width="590" alt="image" src="https://github.com/user-attachments/assets/131d71f8-0986-46b1-9a95-4fbe7581e051">

But still confusing as these parts are overlapping

IMO a simpler representation that focuses on concrete non-overlapping steps with a clear temporal flow rather than abstract groupings would be:

* [p] synaptic vesicle lifecycle [new]
    * [p] synaptic vesicle precursor formation in Golgi [new]
    * [p] synaptic vesicle transport from Golgi to presynapse through axon along cytoskeleton (GO:0099514)
    * [p] synaptic vesicle cycle (GO:0099504)
       * [p] GO:0098700 ! neurotransmitter loading into synaptic vesicle
       * [p] GO:0016079 ! synaptic vesicle exocytosis
           * [p] GO:0016081 ! synaptic vesicle docking
           * [p] GO:0016082 ! synaptic vesicle priming
           * [p] GO:0099502 ! calcium-dependent activation of synaptic vesicle fusion
           * [p] GO:0031629 ! synaptic vesicle fusion to presynaptic active zone membrane
      * [p] GO:0036465 ! synaptic vesicle recycling
           * [p] GO:0048488 ! synaptic vesicle endocytosis
       * [p] GO:0097401 ! synaptic vesicle lumen acidification
       * [p] GO:0097091 ! synaptic vesicle clustering

I kept cycle as-is, I wasn't sure what to do with clustering, overall the cycle should look more like:

<img width="1456" alt="image" src="https://github.com/user-attachments/assets/c301266c-fbba-433e-9df5-2d46cbc96fb6">

My part-root term is perhaps artificial but serves as a useful anchor point. When we have individual GO-CAMs for the steps we can use this structure to derive larger diagrams

_Originally posted by @cmungall in https://github.com/geneontology/go-ontology/issues/29069#issuecomment-2420877286_
