### ISSUE TITLE
obsolete terms differentiated using CHEBI ion (CHEBI:24870)

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#29110]
## P-type ion transporter activity

```yaml
id: GO:0140358
name: P-type transmembrane transporter activity
namespace: molecular_function
def: "Primary active transporter that auto-phosphorylates (hence P) at a key conserved aspartate residue, generating a conformational change that allows transport of the substrate. Hydrolysis of the phosphorylated Asp residue, catalyzed by the actuator (A) domain, results in another state with occluded substrates. Upon dissociation of Mg2+ and Pi, the enzyme reverts to the initial state, in which the counter-transported substrate is released into the cytosol." [PMID:18075584, PMID:25918123]
synonym: "E1-E2 ATPase" EXACT [Wikipedia:P-type_ATPase]
synonym: "P-type ATPase" EXACT [Wikipedia:P-type_ATPase]
xref: TC:3.A.3
xref: Wikipedia:P-type_ATPase
is_a: GO:0042626 ! ATPase-coupled transmembrane transporter activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/20529" xsd:anyURI
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/21273" xsd:anyURI
```

```yaml
id: GO:0015662
name: P-type ion transporter activity
namespace: molecular_function
def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O = ADP + phosphate, to directly drive the transport of ions across a membrane. The reaction is characterized by the transient formation of a high-energy aspartyl-phosphoryl-enzyme intermediate." [PMID:10322420, PMID:10600683]
synonym: "ATPase activity, coupled to transmembrane movement of ions, phosphorylative mechanism" EXACT []
synonym: "ion transmembrane transporter activity, phosphorylative mechanism" RELATED []
synonym: "P-type ATPase activity" EXACT []
synonym: "zinc, cadmium, cobalt, nickel, lead-efflux ATPase activity" NARROW []
intersection_of: GO:0140358 ! P-type transmembrane transporter activity
intersection_of: has_primary_input CHEBI:24870 ! ion
```

GO:0015662 is an only child, it can be merged into the parent. They share exact synonyms differentiated only by "activity". 

In #20529 the string "transmembrane" was removed from the child (because of flippases?) but it remained classified as transmembrane...

## ion binding

```yaml
id: GO:0043167
name: ion binding
namespace: molecular_function
def: "Binding to an ion, a charged atoms or groups of atoms." [GOC:jl]
subset: gocheck_do_not_annotate
subset: goslim_chembl
subset: goslim_metagenomics
subset: goslim_pir
subset: goslim_yeast
synonym: "atom binding" RELATED []
is_a: GO:0036094 ! small molecule binding
intersection_of: GO:0005488 ! binding
intersection_of: has_primary_input CHEBI:24870 ! ion
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26424"
```

was made do-not-annotate in #26424 but could be obsoleted
