### ISSUE TITLE
Split "ice binding" into "ice nucleation" and "antifreeze"

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#29149]
This conflates two different functions

```yaml
id: GO:0050825
name: ice binding
namespace: molecular_function
def: "Binding to ice, water reduced to the solid state by cold temperature. It is a white or transparent colorless substance, crystalline, brittle, and viscoidal." [GOC:curators]
synonym: "antifreeze activity" RELATED []
synonym: "ice crystal binding" EXACT []
synonym: "ice nucleation activity" RELATED []
synonym: "ice nucleation inhibitor activity" RELATED []
is_a: GO:0005488 ! binding
intersection_of: GO:0036094 ! small molecule binding
intersection_of: has_primary_input CHEBI:15377 ! water
```

This should be split into nucleation and antifreeze. The current experimental annotations are antifreeze proteins, so a replaced_by would be OK here. We also get plenty of annotations from mappings.

```yaml
name: ice nucleation activity
def: "catalyzes the formation of ice crystals in extracellular fluid at relatively high temperatures (up to -2 degrees Celsius) to protect the organism from damage by intracellular ice formation.. This process is commonly found in certain bacteria, such as Pseudomonas syringae, and plays roles in environmental adaptation and plant pathogenesis." [KW-0387, [35551271](https://pubmed.ncbi.nlm.nih.gov/35551271/)]
in_taxon: Bacteria
exact: https://www.uniprot.org/keywords/KW-0387 ! ice nucleation
xref: TCDB:9.B.133.1.1
```

```yaml
name: antifreeze activity
def: "inhibits the growth and recrystallization of ice crystals, thereby lowering the freezing point of water and preventing cellular damage at subzero temperatures. This activity is observed in various cold-adapted organisms, including certain fish, insects, and plants, and contributes to survival in extreme cold environments by stabilizing supercooled liquid states"
xref: https://www.ebi.ac.uk/interpro/entry/InterPro/IPR000104/ ! antifreeze 1
```

In addition to the mappings above we'd want to change

* https://www.uniprot.org/unirule/UR000150976 unirule for antifreeze

There may be an argument for keeping ice binding and having the two new terms connect to it via has-part, there may be some similarities in structure. Both AFPs and INPs exhibit repetitive sequences and beta-helical structures that allow them to interact with water molecules. INPs, like those found in Pseudomonas syringae, utilize a large ice-binding surface that promotes ice nucleation by providing a scaffold for ice crystals to form, while AFPs have a smaller ice-binding area that binds to nascent ice and inhibits its growth [(Graether & Jia, 2001)](https://consensus.app/papers/modeling-pseudomonas-syringae-icenucleation-protein-graether/1fa135e7f74258d3b1a06f28a0d96989/?utm_source=chatgpt). But IMO this is unneeded complication and GO should represent the function not the binding.

I am not sure what to suggest for parent terms. It seems we have a lot of terms floating at the root in MF right now. This ticket is not urgent so perhaps we could come up with a general solution for that first.
