### ISSUE TITLE
biosynthesis processes that are single-step in some organisms and multi-step in others

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#29672]
Consider this process

```yaml
id: GO:0009229
name: thiamine diphosphate biosynthetic process
namespace: biological_process
def: "The chemical reactions and pathways resulting in the formation of thiamine diphosphate, a derivative of thiamine (vitamin B1) which acts as a coenzyme in a range of processes including the Krebs cycle." [GOC:jl, ISBN:0140512713]
synonym: "thiamin diphosphate biosynthetic process" EXACT [GOC:cuators]
synonym: "thiamin pyrophosphate biosynthesis" EXACT []
synonym: "thiamin pyrophosphate biosynthetic process" EXACT []
synonym: "thiamine diphosphate anabolism" EXACT []
synonym: "thiamine diphosphate biosynthesis" EXACT []
synonym: "thiamine diphosphate formation" EXACT []
synonym: "thiamine diphosphate synthesis" EXACT []
synonym: "thiamine pyrophosphate biosynthesis" EXACT []
synonym: "thiamine pyrophosphate biosynthetic process" EXACT []
synonym: "TPP biosynthesis" EXACT []
synonym: "TPP biosynthetic process" EXACT []
intersection_of: GO:0009058 ! biosynthetic process
intersection_of: has_primary_output CHEBI:58937 ! thiamine(1+) diphosphate(3-)
```

the start point is undefined (formally or informally)

Some euks, such as plants and yeast have a whole pathway for this, and the annotations in these species look more or less what you might expect (with a few annotations that seem to be indirect roles). In all cases the penultimate step is making thiamine, when is then turned into ThDP by TPK1.

But we mammals rely on other organisms to make thiamine, and our "thiamine diphosphate biosynthetic process (sensu stricto)" is **trivially the activity of a single gene** (TPK1). Ideally we would see only one human gene annotated to this "pathway" -- and in fact we do, if we look only at IBAs. But there is a lot of annotation of genes (THTPA, SLC19A2, SLC19A3, SLC25A19) that are related in some other way.

These other annotations make sense when we look at what Reactome calls "thiamin metabolism" https://reactome.org/PathwayBrowser/#/R-HSA-196819

<img width="1031" alt="Image" src="https://github.com/user-attachments/assets/20dacd29-67b8-4af2-83f1-e828bf97fa52" />

I think Reactome's use of the catch-all "metabolism" is right here, because really it's only one step here that is biosynthesis (TPK1).

IMO it's clear the PAINT annotators and other annotators are annotating to a different concept here.

My proposal here is to ban single-step pathways, restrict ThDP biosynthesis to be bacteria, plants, yeast, etc. However, I do think it's useful to have a concept for what is shown in the Reactome diagram and retain the same genes. ThDP transport (no such term in GO) isn't quite right since it's really uptake-modification-transport. Metabolism is not wrong but we use metabolism as a general grouping.

This would be a bit of work and reannotation. But right now the concept we have in GO is being interpreted in at least two different ways which is not good.
