### ISSUE TITLE
Remove RHEA xrefs under non-catalytic activities and add a check

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#29878]
These are all mapped to the same RHEA:

<img width="413" alt="Image" src="https://github.com/user-attachments/assets/a696c82a-f5cb-4036-92b2-ba2d6ebf4c23" />

```yaml
id: GO:0140665
name: ATP-dependent H3-H4 histone complex chaperone activity
namespace: molecular_function
def: "A histone chaperone that carries a H3-H4 histone complex, driven by ATP hydrolysis." [PMID:31848341, PMID:33658433]
synonym: "ATP-dependent H3-H4 histone complex loader activity" NARROW []
synonym: "H3-H4 dimer loading activity" EXACT []
synonym: "H3-H4 histone chaperone" BROAD []
synonym: "H3-H4 histone complex loader activity" BROAD []
synonym: "histone chaperone" RELATED []
synonym: "histone H3-H4 dimer loading activity" EXACT []
xref: RHEA:13065 {source="skos:broadMatch"}
is_a: GO:0000510 ! H3-H4 histone complex chaperone activity
is_a: GO:0140674 ! ATP-dependent histone chaperone activity
relationship: has_part GO:0016887 ! ATP hydrolysis activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/21580" xsd:anyURI
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/21733" xsd:anyURI
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28520" xsd:anyURI

id: GO:0140849
name: ATP-dependent H2AZ histone chaperone activity
namespace: molecular_function
def: "A histone chaperone that mediates the exchange of histone H2A-H2B dimer and histone H2AZ-H2B dimers in a nucleosome, driven by ATP hydrolysis. Some chaperones insert H2AZ-H2B dimers and remove H2A-H2B, while others do the opposite." [PMID:21241891, PMID:23580526, PMID:30309918]
comment: Drosophila H2AV corresponds to histone H2AZ.
synonym: "ATP-dependent H2A.Z histone chaperone activity" EXACT []
synonym: "H2AZ histone exchange activity" RELATED []
xref: RHEA:13065 {source="skos:broadMatch"}
is_a: GO:0140674 ! ATP-dependent histone chaperone activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/23463" xsd:anyURI
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28520" xsd:anyURI
```

even though these are marked "broad" I still think these are wrong. If we want to capture "driven by ATP hydrolysis" do this via an actual ontology edge
