### ISSUE TITLE
Missing EC and typos in NAD(P)H oxidase H2O2-forming triad

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#29964]
current:

```yaml
[Term]
id: GO:0016174
name: NAD(P)H oxidase H2O2-forming activity
namespace: molecular_function
def: "Catalysis of the reaction: NAD(P)H + H+ + O2 = NAD(P)+ + hydrogen peroxide." [EC:1.6.3.1, PMID:10401672, PMID:10601291, PMID:11822874]
synonym: "dual oxidase activity" RELATED [EC:1.6.3.1]
synonym: "NAD(P)H oxidase activity" BROAD []
synonym: "NAD(P)H:oxygen oxidoreductase activity" RELATED [EC:1.6.3.1]
synonym: "NADPH oxidase" BROAD [EC:1.6.3.1]
synonym: "p138tox" RELATED [EC:1.6.3.1]
synonym: "ThOX activity" NARROW [EC:1.6.3.1]
synonym: "THOX2 activity" NARROW [EC:1.6.3.1]
synonym: "thyroid NADPH oxidase activity" NARROW []
synonym: "thyroid oxidase 2 activity" NARROW [EC:1.6.3.1]
synonym: "thyroid oxidase activity" NARROW [EC:1.6.3.1]
xref: EC:1.6.3.1 {source="skos:exactMatch"} ! EC 1.6.3.1 NAD(P)H oxidase (H2O2-forming)
is_a: GO:0050664 ! oxidoreductase activity, acting on NAD(P)H, oxygen as acceptor
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28776" xsd:anyURI

[Term]
id: GO:0106293
name: NADH oxidase H202-forming activity
namespace: molecular_function
def: "Catalysis of the reaction: NADH + H+ + O2 = NAD + hydrogen peroxide (H2O2)." [RHEA:11264]
xref: RHEA:11264
is_a: GO:0016174 ! NAD(P)H oxidase H2O2-forming activity
created_by: hjd
creation_date: 2020-08-19T17:35:22Z

[Term]
id: GO:0106294
name: NADPH oxidase H202-forming activity
namespace: molecular_function
def: "Catalysis of the reaction: NADPH + H+ + O2 = NADP + hydrogen peroxide (H2O2)." [RHEA:11260]
xref: RHEA:11260
is_a: GO:0016174 ! NAD(P)H oxidase H2O2-forming activity
created_by: hjd
creation_date: 2020-08-19T17:38:36Z
```

* missing `EC 1.6.3.3 NADH ! oxidase (H2O2-forming)` xref on non-P
* typo - should be `H2O2` not `H202`, unless this is a very unusual enzyme
