### ISSUE TITLE
tachyzoite dense granule

### ISSUE THREAD

**Issue by brendamg** [geneontology/go-ontology#29986]
Please provide as much information as you can: 

* **tachyzoite dense granule:**

* **Definition (free text)**
???

* **Reference, in format PMID:#######**
PMID: [35083211](https://pubmed.ncbi.nlm.nih.gov/35083211/)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers.
* ec3_1_3.16 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
* id: GO:0020026
name: merozoite dense granule
we need it for Localization of ec 3.1.3.16, could this be a broad synonym?

**Comment by pgaudet** [comment]
Is this different from 'GO:0031045 dense core granule'? 

(maybe GO:0020026  merozoite dense granule also represents that same term?)

**Comment by cmungall** [comment]
I'm going to consolidate some other discussion here

First, I think the current situation in GO is suboptimal, we have a term for the apicomplexan DCG, but it is for some reason restricted to a particular stage:

```yaml
id: GO:0020026
name: merozoite dense granule
namespace: cellular_component
def: "Electron-dense organelle with a granular internal matrix found throughout the merozoite life cycle stage of apicomplexan parasites; contains proteins destined to be secreted into the parasitophorous vacuole following parasite invasion of a host cell." [GOC:mb, GOC:mtg_sensu]
synonym: "dense body" RELATED []
is_a: GO:0031410 ! cytoplasmic vesicle
```

This leaves people in a difficult position if they want to annotate e.g. GRA1 which is clearly found in the tachyzoite stage.

One solution is that we generalize GO:0020026 to be all applicable phases of the apicomplexan lifecycle. This would require no new terms, and would be suitable for capturing GRA1 etc

Do the apicomplexan community feel it is necessary to capture the stage in the GO term? Would you prefer it if there were distinct terms for tachyzoite, merozoite? This would entail more complexity for GO and for the user querying, compared to using OPL in an annotation extension

@brendamg @EmilyBowlerBarnett what are your thoughts?
